name: brokoli
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.7
  cupertino_icons: ^1.0.6
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  get: 4.6.6
  get_cli: 1.8.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
